name: Infrastructure CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-infra:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Loops through dev and prod folders sequentially
        environment: [dev, prod]
    
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Setup HashiCorp Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      # Checks formatting across your targeted workspace
      - name: Check code formatting style
        run: terraform fmt -check
        working-directory: ./infra/envs/${{ matrix.environment }}

      # Initializes modules and configuration layers locally
      - name: Initialize workspace backend
        run: terraform init -backend=false
        working-directory: ./infra/envs/${{ matrix.environment }}

      # Serves as the ultimate offline dry-run step
      - name: Validate environment syntax
        run: terraform validate
        working-directory: ./infra/envs/${{ matrix.environment }}
