name: Infrastructure CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  terraform-check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Check formatting
        run: terraform fmt -check
        working-directory: ./infra

      - name: Initialize
        run: terraform init
        working-directory: ./infra

      - name: Validate configuration
        run: terraform validate
        working-directory: ./infra

      - name: Plan (Dry-Run)
        run: terraform plan -no-color
        working-directory: ./infra
